### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by stoltenhoff** [madpink/couchdb4livecode#5]
Sorry for posting this silly question here, but as LiveCode-newbie i'm completely lost: 
How to »install« the library? Is it just a library? I copied the .livecodescript to 
LiveCode Indy (9.6.1)/Contents/Tools/Tollset/libraties but can't figure out, how to work 
with the commands. Is there any demo file, like the one from the YouTube video, too? 
Thanks a lot! Jan.

**Comment by madpink** [comment]
you don't install into Livecode, you just add it to your project

you can:
-copy and paste into a script such as a card or stack script
-put into a script of a substack
-keep it as an external script and include it (most useful if you are using in multiple stacks and making frequent changes)

I usually create a button with the library script and insert into backscripts
`insert the script of button "Library-CouchDB" into back`

check out the Wiki for a few examples

**Comment by stoltenhoff** [comment]
Thank you for your help! I will try again. 
By the way: loving your udemy course.
